### ISSUE TITLE
[META]  Make Site Resposive

### ISSUE THREAD

**Issue by aa-deet-eeya** [glugmvit/gwoc#15]
- [x] About Us Section: Image Carousel

- [x] Register Section: Register Cards, make Register buttons mobile friendly 

- [x] Add Transition animation to Hamburger menu icon on click

- [x] Improve the floating Navigation menu on mobile ( currently the menu fades onclick only after scrolling is done, improve transition time )
- [x] Add the circle button on mobile (added screenshot for further reference)

<img src="https://user-images.githubusercontent.com/26107248/97079094-d1ca9580-160e-11eb-87b9-b7052733b471.png" width="20%" />  <img src="https://user-images.githubusercontent.com/26107248/97079084-be1f2f00-160e-11eb-80bb-c55e9e68a724.jpg" width="75%" />
